### ISSUE TITLE
App crash on Andorid

### ISSUE THREAD

**Issue by aBuder** [Instabug/Instabug-Flutter#107]
If I install the instabug flutter plugin, I get the following error, when I start the plugin.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.test.mobile_app.dev, PID: 15660
    java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
        at com.instabug.library.screenshot.a.a(ScreenshotManager.java:48)
        at com.instabug.library.screenshot.a$a.run(ScreenshotManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by AliAbdelfattah** [comment]
Hi @aBuder, thanks for reporting this. Could you provide these info please?
- SDK version.
- Your integration code
- Steps to reproduce the error
