### ISSUE TITLE
Instabug.show() and BugReporting.show(...) crashes on Android

### ISSUE THREAD

**Issue by knyghtryda** [Instabug/Instabug-Flutter#112]
Instabug_flutter version is 9.0.6.  

```dart
PlatformIconButton(
      icon: Icon(Icons.feedback),
      onPressed: () => Instabug.show(),
    );
```
Previously, I had a separate BugReporting.show(...) for each ReportType.  This worked fine on iOS.  However, this causes a crash to homescreen on Android.  I changed to Instabug.show() and this also crashes to homescreen for Android.

**Comment by AliAbdelfattah** [comment]
Hi @knyghtryda, thanks for reporting this. Have you followed our Android integration steps here https://github.com/Instabug/Instabug-Flutter/blob/master/README.md#using-instabug ?

If so, could you send your Android integration code please? Also, crash details would be useful to share :)

**Comment by knyghtryda** [comment]
Here's the integration code.
```kotlin
class CustomFlutterApplication : FlutterApplication() {
    override fun onCreate() {
        super.onCreate()
        val invocation_events = ArrayList<String>()
        invocation_events.add(InstabugFlutterPlugin.INVOCATION_EVENT_SCREENSHOT)
        val instabug = InstabugFlutterPlugin()
        instabug.start(this@CustomFlutterApplication, "API_TOKEN", invocation_events)
    }
}
```
Here's the stacktrace from crashlytics:
```
Fatal Exception: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
       at android.os.Parcel.createException(Parcel.java:2071)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.os.Parcel.readException(Parcel.java:1987)
       at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
       at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
       at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
       at com.instabug.library.screenshot.a.a(ScreenshotManager.java:50)
       at com.instabug.library.screenshot.a$a.run(ScreenshotManager.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by AliAbdelfattah** [comment]
Hi @knyghtryda, could you make sure you're building with Android 29?

Check the build.gradle file:
 ```
 compileSdkVersion = 29
 buildToolsVersion = '29.0.3'
```
