### ISSUE TITLE
Surveys Crash on Android

### ISSUE THREAD

**Issue by adityadroid** [Instabug/Instabug-Flutter#122]
I am trying to use Surveys on Android but Instabug crashes. Here's the stacktrace:
 ```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/OneShotPreDrawListener;
        at androidx.fragment.app.FragmentManagerImpl$EndViewTransitionAnimation.getTransformation(FragmentManagerImpl.java:3464)
        at android.view.animation.Animation.getTransformation(Animation.java:1061)
        at androidx.fragment.app.FragmentManagerImpl$EndViewTransitionAnimation.getTransformation(FragmentManagerImpl.java:3476)
        at android.view.View.applyLegacyAnimation(View.java:21148)
        at android.view.View.draw(View.java:21264)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4198)
        at android.view.View.draw(View.java:21597)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:580)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:586)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:659)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3871)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3671)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2993)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8018)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
        at android.view.Choreographer.doCallbacks(Choreographer.java:986)
        at android.view.Choreographer.doFrame(Choreographer.java:902)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.OneShotPreDrawListener"
```

Steps to reproduce:
1. Create an App Rating Survey using the default template with Auto Targetting.
2. Run the app on an Android device.
3. Choose "No"/negative response when prompted if you like the app or not.
4. Try typing in the feedback field after that.
5. App crashes.

**Comment by AliAbdelfattah** [comment]
Hi @adityadroid, thanks for reporting this. Could you please provide this info to further investigate the issue?
- Instabug-Flutter version
- `compileSdkVersion` from `build.gradle`
- Whether AndroidX is enabled

**Comment by adityadroid** [comment]
> Hi @adityadroid, thanks for reporting this. Could you please provide this info to further investigate the issue?
> 
>     * Instabug-Flutter version
> 
>     * `compileSdkVersion` from `build.gradle`
> 
>     * Whether AndroidX is enabled
@AliAbdelfattah Here are the details:-
instabug_flutter: ^9.1.0
compileSdkVersion: 29
AndroidX Enabled : yes

**Comment by adityadroid** [comment]
Any updates on this issue? @AliAbdelfattah  @alyezz

**Comment by AliAbdelfattah** [comment]
@adityadroid this seems to be related to a compatibility issue related to AndroidX. Are you currently in the process of upgrading your project to AndroidX? It'd help if you could list your Android dependencies as well.

**Comment by adityadroid** [comment]
> @adityadroid this seems to be related to a compatibility issue related to AndroidX. Are you currently in the process of upgrading your project to AndroidX? It'd help if you could list your Android dependencies as well.

Here are the android dependencies:
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}
```

**Comment by adityadroid** [comment]
> > @adityadroid this seems to be related to a compatibility issue related to AndroidX. Are you currently in the process of upgrading your project to AndroidX? It'd help if you could list your Android dependencies as well.
> 
> Here are the android dependencies:
> 
> ```
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.1.0'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
> }
> ```

Any updates on how to fix it? @AliAbdelfattah

**Comment by AliAbdelfattah** [comment]
@adityadroid we have been trying to reproduce the issue with no luck. Could you try reproducing it on our sample app, please?
