### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by stwonary** [Instabug/Instabug-Flutter#143]
When init in Flutter with`Instabug.start` is crashing on Android

```
I/flutter (11909): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (11909): The following MissingPluginException was thrown:
I/flutter (11909): MissingPluginException(No implementation found for method startWithToken:invocationEvents: on
I/flutter (11909): channel instabug_flutter)
I/flutter (11909): 
I/flutter (11909): When the exception was thrown, this was the stack:
I/flutter (11909): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
I/flutter (11909): <asynchronous suspension>
I/flutter (11909): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
I/flutter (11909): #2      Instabug.start (package:instabug_flutter/Instabug.dart:105:20)
I/flutter (11909): #3      _LandingScreenState.initState (package:_____/screens/landing/landing_screen.dart:22:14)
I/flutter (11909): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
I/flutter (11909): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (11909): ...     Normal element mounting (24 frames)
I/flutter (11909): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (11909): #30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
I/flutter (11909): ...     Normal element mounting (136 frames)
I/flutter (11909): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (11909): #167    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
I/flutter (11909): ...     Normal element mounting (285 frames)
I/flutter (11909): #452    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (11909): #453    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (11909): #454    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
```

**Comment by AliAbdelfattah** [comment]
Hi @stwonary, thanks for reporting this. Could you please share the SDK version and your integration code?

**Comment by stwonary** [comment]
sure! 

Flutter
```
➜ flutter --version
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (13 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

Instabug SDK
```
  instabug_flutter:
    dependency: "direct main"
    description:
      name: instabug_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.1.6"
```

Integration code in my first Screen
```
      Instabug.start('token', [InvocationEvent.shake]);
```

**Comment by AliAbdelfattah** [comment]
I think you may have missed the Android steps [here](https://github.com/Instabug/Instabug-Flutter#initializing-instabug). Please let me know if this isn't the case.

**Comment by stwonary** [comment]
I think the problem is at

https://github.com/Instabug/Instabug-Flutter/blob/154b1c1c5dfdb1a9da262b233c4dc0909c9d413b/lib/Instabug.dart#L106

and

https://github.com/Instabug/Instabug-Flutter/blob/154b1c1c5dfdb1a9da262b233c4dc0909c9d413b/android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java#L87

https://github.com/Instabug/Instabug-Flutter/blob/154b1c1c5dfdb1a9da262b233c4dc0909c9d413b/android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java#L131

The invoke method's name doesn't match Android's implementation.

**Comment by stwonary** [comment]
I prefer not to init in my Application.java. I want to init it after the user logged in.

**Comment by AliAbdelfattah** [comment]
@stwonary I'm afraid this isn't possible. You'll have to initialize it in your Application file, it won't work otherwise.

**Comment by stwonary** [comment]
okay, I see. Thank you
