### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by britov** [Instabug/Instabug-Flutter#168]
After call `Instabug.show`

Bug report 
```
data:text/text;charset=utf-8,
java.lang.NoSuchMethodError: No static method asAttributeSet(Lh/c/a/a;)Landroid/util/AttributeSet; in class Landroid/util/Xml; or its super classes (declaration of 'android.util.Xml' appears in /system/framework/framework.jar!classes2.dex)
	 at androidx.appcompat.c.g.inflate(SupportMenuInflater.java:4)
	 at com.instabug.bug.view.reporting.b.onCreateOptionsMenu(BaseReportingFragment.java:1)
	 at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:3)
	 at androidx.fragment.app.j.a(FragmentManagerImpl.java:542)
	 at androidx.fragment.app.f.a(FragmentController.java:11)
	 at androidx.fragment.app.d.onCreatePanelMenu(FragmentActivity.java:2)
	 at androidx.appcompat.c.i.onCreatePanelMenu(WindowCallbackWrapper.java:1)
	 at androidx.appcompat.app.h$k.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
	 at androidx.appcompat.c.i.onCreatePanelMenu(WindowCallbackWrapper.java:1)
	 at androidx.appcompat.app.k.o(ToolbarActionBar.java:5)
	 at androidx.appcompat.app.k$a.run(ToolbarActionBar.java:1)
	 at android.os.Handler.handleCallback(Handler.java:914)
	 at android.os.Handler.dispatchMessage(Handler.java:100)
	 at android.os.Looper.loop(Looper.java:224)
	 at android.app.ActivityThread.main(ActivityThread.java:7560)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
	 
	 
	 Android10 (v10)(Level 29)
	 Xiaomi Mi 9T Pro

**Comment by AliAbdelfattah** [comment]
Thank you for reporting this. What SDK version are you on? Are you able to reproduce it consistently?

**Comment by britov** [comment]
version: "9.1.8"
It happened every time after call `Instabug.show` method
I think it related with the Shrink mode on android because all works fine when i use --no-shrink arg
But i don't know how to fix it for the shrink mode 
 Can we add some packages to a proguard file as an exсept?

**Comment by MahmoudMehisen** [comment]
@britov Issue now solved by latest SDK version, you can upgrade your SDK to solve this issue
