### ISSUE TITLE
Issue : No implementation found for method startWithToken:invocationEvents: on channel instabug_flutter

### ISSUE THREAD

**Issue by daadu** [Instabug/Instabug-Flutter#78]
```
Unhandled Exception: MissingPluginException(No implementation found for method startWithToken:invocationEvents: on channel instabug_flutter)
```

I am using the latest version of [instabug plugin on pub ](https://pub.dev/packages/instabug), getting the above error when calling `Instabug.start(..)` in `initState`

**Comment by talmor-guy** [comment]
Same for identify user:

MissingPluginException(No implementation found for method identifyUserWithEmail:name: on channel instabug_flutter)

**Comment by HeshamMegid** [comment]
Sorry, this fell off our radar. We're looking into it now.

**Comment by salmamali** [comment]
@daadu is this when running on Android or iOS? This could happen if you're using the wrong format of the API, can you send me the exact format of `Instabug.start` you're using as well?

**Comment by csandeep** [comment]
I have the same exact issue , on `Android`. 
This is how Im invoking the `start`

```
      Instabug.start(Strings.TM_INSTABUG_KEY, <InvocationEvent>[InvocationEvent.shake]);
```

The error stack is 
```E/flutter (23912): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method startWithToken:invocationEvents: on channel instabug_flutter)
E/flutter (23912): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (23912): <asynchronous suspension>
E/flutter (23912): #1      Instabug.start (package:instabug/Instabug.dart:103:20)
E/flutter (23912): <asynchronous suspension>
E/flutter (23912): #2      TMMainState.initPlatformState (package:themighty/main.dart:96:16)
E/flutter (23912): <asynchronous suspension>
E/flutter (23912): #3      TMMainState.initState (package:themighty/main.dart:87:5)
E/flutter (23912): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (23912): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (23912): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (23912): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (23912): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (23912): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (23912): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (23912): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (23912): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (23912): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (23912): #14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
E/flutter (23912): #15     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
E/flutter (23912): #16     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
E/flutter (23912): #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
E/flutter (23912): #18     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
E/flutter (23912): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
E/flutter (23912): #20     runApp (package:flutter/src/widgets/binding.dart:780:7)
E/flutter (23912): #21     main (package:themighty/main.dart:34:16)
E/flutter (23912): #22     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
E/flutter (23912): #23     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (23912): #24     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (23912): #25     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (23912): #26     runZoned (dart:async/zone.dart:1500:12)
E/flutter (23912): #27     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
E/flutter (23912): #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
E/flutter (23912): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
E/flutter (23912): 
```

**Comment by csandeep** [comment]
there are couple of issues here:
   * the Android plugin has no `startWithToken` method
   * even if I make a call to the `instabug_flutter` manually to get to the implemented `start` method there is a bug in the implementation where the introspected `method.invoke` fails to pass the right number of arguments (https://github.com/Instabug/Instabug-Flutter/blob/98f3c3c4a63220b7600f99dc3f1aff46c5e470af/android/src/main/java/com/instabug/instabugflutter/InstabugFlutterPlugin.java#L84)

my code 
```
   MethodChannel _channel = MethodChannel('instabug_flutter');
    final List<String> invocationEventsStrings = <String>[];

    final List<dynamic> params = <dynamic>[Strings.TM_INSTABUG_KEY, invocationEventsStrings];
    await _channel.invokeMethod<Object>('start', params);
```

Here's the stack trace from Logcat
```2019-06-26 18:17:00.438 24957-24957/com.themighty W/System.err: java.lang.IllegalArgumentException: Wrong number of arguments; expected 3, got 2
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at com.instabug.instabugflutter.InstabugFlutterPlugin.onMethodCall(InstabugFlutterPlugin.java:84)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at android.os.Looper.loop(Looper.java:142)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-06-26 18:17:00.439 24957-24957/com.themighty W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)```

**Comment by alyezz** [comment]
@csandeep There is no start method on the android channel because its initialized in the Main Application class, check Integration steps 4 & 5 in our [Readme ](https://github.com/Instabug/Instabug-Flutter/blob/master/README.md)

you should check for the device running before calling `start`

```
      if (Platform.isIOS) {
        Instabug.start('YOUR_TOKEN', <InvocationEvent>[InvocationEvent.shake]);
      }
```
