### ISSUE TITLE
Linker error with new flutter project

### ISSUE THREAD

**Issue by hffmnn** [Instabug/Instabug-Flutter#81]
I have 2 problems when trying to use Instabug on a newly created project.

1. cocoapods can not resolve the dependencies, because the default minmum deployment target is to low
2. The linker can not find symbols (for the Simulator, did not try for device)

Here are the steps I did to trigger the errors:

---
`flutter create -i swift -a kotlin --project-name instatest instatest`

```bash
Creating project instatest...
  instatest/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  instatest/ios/Runner/Info.plist (created)
  instatest/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  instatest/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  instatest/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  instatest/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  instatest/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  instatest/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  instatest/ios/Runner/Base.lproj/Main.storyboard (created)
  instatest/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  instatest/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  instatest/ios/Flutter/Debug.xcconfig (created)
  instatest/ios/Flutter/Release.xcconfig (created)
  instatest/ios/Flutter/AppFrameworkInfo.plist (created)
  instatest/test/widget_test.dart (created)
  instatest/instatest.iml (created)
  instatest/.gitignore (created)
  instatest/.metadata (created)
  instatest/android/app/src/profile/AndroidManifest.xml (created)
  instatest/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  instatest/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  instatest/android/app/src/main/res/drawable/launch_background.xml (created)
  instatest/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  instatest/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  instatest/android/app/src/main/res/values/styles.xml (created)
  instatest/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  instatest/android/app/src/main/AndroidManifest.xml (created)
  instatest/android/app/src/debug/AndroidManifest.xml (created)
  instatest/android/gradle/wrapper/gradle-wrapper.properties (created)
  instatest/android/gradle.properties (created)
  instatest/android/settings.gradle (created)
  instatest/android/app/build.gradle (created)
  instatest/android/app/src/main/kotlin/com/example/instatest/MainActivity.kt (created)
  instatest/android/build.gradle (created)
  instatest/android/.gradle/5.0/fileHashes/fileHashes.lock (created)
  instatest/android/instatest_android.iml (created)
  instatest/pubspec.yaml (created)
  instatest/README.md (created)
  instatest/ios/Runner/Runner-Bridging-Header.h (created)
  instatest/ios/Runner/AppDelegate.swift (created)
  instatest/ios/Runner.xcodeproj/project.pbxproj (created)
  instatest/lib/main.dart (created)
  instatest/.idea/runConfigurations/main_dart.xml (created)
  instatest/.idea/libraries/Flutter_for_Android.xml (created)
  instatest/.idea/libraries/Dart_SDK.xml (created)
  instatest/.idea/libraries/KotlinJavaRuntime.xml (created)
  instatest/.idea/modules.xml (created)
  instatest/.idea/workspace.xml (created)
Running "flutter packages get" in instatest...                      3.1s
Wrote 66 files.

All done!
[✓] Flutter is fully installed. (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-GB)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices is fully installed. (Xcode 10.2.1)
[✓] Android Studio is fully installed. (version 3.4)
[✓] VS Code is fully installed. (version 1.35.1)
[✓] Connected device is fully installed. (1 available)

In order to run your application, type:

  $ cd instatest
  $ flutter run

Your application code is in instatest/lib/main.dart.
```

---

```
cd instatest && flutter run 
```

All good. App is running in the Simulator.

---

Adding `instabug: ^1.0.0-beta.4` to the `pubspec.yaml` as described in the docs `flutter run` gives this, which is the first problem:

```
Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...                                              0.7s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `instabug` from `.symlinks/plugins/instabug/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "instabug":
      In Podfile:
        instabug (from `.symlinks/plugins/instabug/ios`)

    Specs satisfying the `instabug (from `.symlinks/plugins/instabug/ios`)` dependency were found, but they required a higher minimum deployment target.

    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/resolver.rb:88:in `resolve'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:64:in `section'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:398:in `analyze'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:64:in `section'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:156:in `install!'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/command/install.rb:51:in `run'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/command.rb:52:in `run'
    ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/bin/pod:55:in `<top (required)>'
    ~/.rbenv/versions/2.5.3/bin/pod:23:in `load'
    ~/.rbenv/versions/2.5.3/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 5s.
```

---

After setting `platform :ios, '10.0'` in the `Podfile`, `flutter run` gives this result:

```
=== BUILD TARGET instabug OF PROJECT Pods WITH CONFIGURATION Debug ===
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_IBGFeatureRequests", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_IBGReplies", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_IBGChats", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_IBGBugReporting", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_Instabug", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
         (maybe you meant: _OBJC_CLASS_$_InstabugFlutterPlugin)
      "_kIBGBetaWelcomeMessageFinishStepTitle", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGBetaWelcomeMessageWelcomeStepContent", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGBetaWelcomeMessageFinishStepContent", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGAddScreenRecordingMessageStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGLiveWelcomeMessageTitle", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGThankYouAlertTitleStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGRecordingMessageToHoldTextStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGAudioRecordingPermissionDeniedTitleStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGShakeStartAlertTextStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGChatReplyFieldPlaceholderStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGInvalidEmailMessageStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGChatsTitleStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGLiveWelcomeMessageContent", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGInvalidCommentMessageStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGBetaWelcomeMessageHowToReportStepTitle", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGAddExtraScreenshotStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGThankYouAlertMessageStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_IBGSurveys", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_kIBGAddImageFromGalleryStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGAddVoiceMessageStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGCommentFieldPlaceholderForFeedbackStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_OBJC_CLASS_$_IBGLog", referenced from:
          objc-class-ref in InstabugFlutterPlugin.o
      "_kIBGCommentFieldPlaceholderForBugReportStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGRecordingMessageToReleaseTextStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGReportFeedbackStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGInvocationTitleStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGEmailFieldPlaceholderStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGReportBugStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGBetaWelcomeMessageWelcomeStepTitle", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGBetaWelcomeMessageHowToReportStepContent", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
      "_kIBGEdgeSwipeStartAlertTextStringName", referenced from:
          +[InstabugFlutterPlugin constants] in InstabugFlutterPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 5s.
```
---
My dependencies:

```
✗ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!
```
---

```
✗ pod --version
1.7.3
```

Can anyone reproduce this problem? Any help would be appreciated, because I have no idea where the problem is coming from.

**Comment by HeshamMegid** [comment]
@hffmnn this issue seems to be happening with Swift projects only. We're looking into a fix.

**Comment by alyezz** [comment]
@hffmnn this seems to be a known issue in flutter. see [here] (https://github.com/flutter/flutter/issues/9694).

You can fix this by opening your pod file and commenting `use_frameworks! `: 

 In your podfile where You see
 ```
 target 'Runner' do
   use_frameworks!  
 ```
 comment user_frameworks!
 ```
target 'Runner' do
   # use_frameworks!  
 ```

**Comment by satjawat** [comment]
@alyezz  I have the problem too. I think this relative with this [issue](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/42) and I already remove user_frameworks from my pod file.

**Comment by hffmnn** [comment]
Hi @alyezz and thanks for the response.

I tried your suggestion but that gives a lot of new build errors, not necessarily related to Instabug but other pod dependencies we have in our project.

In between I found a possible fix that seems to work:

Firstly [I found out](https://github.com/CocoaPods/CocoaPods/issues/8502#issuecomment-462212091), that everything seems to work with Cocoapods version < `1.5.3`, so it looks like something changed in between `1.5.3` and the later Cocoapods versions. So I went ahead and did a diff between a working version and one that does not work. Turns out, that Cocoapods removes `OTHER_LDFLAGS = -framework "Flutter" -framework "Instabug"`  from the `xcconfig` file it generates (it does that for all our dependencies but only Instabug seems to have a problem with that change).

Reverting that change via a `post_install` hook in our `Podfile` seems to fix the problem:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      if target.name == "instabug_flutter"
        config.build_settings["OTHER_LDFLAGS"] = '-framework "Flutter" -framework "Instabug"'
      end
    end
  end
end
```

Another possible fix could be done on your side: When updating `` with this line `s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-framework "Flutter" -framework "Instabug"'` it also seems to work.

I have no idea what the implications of these changes are, I just wanted to give you a quick update on my current state.

Note: This fix only seems to work with versions before the renaming from `instabug_flutter` to `instabug`. With the new naming scheme I get a runtime error on app startup:

```
dyld: Library not loaded: @rpath/instabug.framework/instabug
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/A492F77E-098D-46D9-A3C1-A77CBE2C443A/data/Containers/Bundle/Application/B1249BFC-33AE-4A74-AB24-C2137EA1A3D6/Runner.app/Runner
  Reason: image not found
```

**Comment by HeshamMegid** [comment]
@hffmnn thank you so much for digging into this. This is very helpful!

We're currently looking into a permanent fix based on your findings for both CocoaPods and the possible conflict because of APFS.

**Comment by alyezz** [comment]
@hffmnn we just released 1.0.0-beta.5 with a fix for this issue, please update and let us know!

**Comment by hffmnn** [comment]
Hi @alyezz,

thanks for this update. I updated my project, but sadly it does not compile. I guess it still has to do with the renaming from `instabug_flutter` to `instabug`.

Here are the steps to reproduce:

* `flutter create -i swift testertest` && cd testertest
* Add `instabug: ^1.0.0-beta.5` as dependency
* Update the Podfile with `platform :ios, '10.0'`, else it gives

```
[!] CocoaPods could not find compatible versions for pod "instabug":
  In Podfile:
    instabug (from `.symlinks/plugins/instabug/ios`)

Specs satisfying the `instabug (from `.symlinks/plugins/instabug/ios`)` dependency were found, but they required a higher minimum deployment target.
```

* Open an iOS Simulator and `flutter run`

This gives the following error:

```
Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...                                              1.0s
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           1.1s
 └─Compiling, linking and signing...                         1.3s
Xcode build done.                                            4.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then
    disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner')
    <built-in>:1:10: warning: non-portable path to file '"~/Desktop/instabugger/testertest/ios/Pods/Target Support Files/Instabug/instabug-prefix.pch"'; specified path differs in case from file name on disk
    [-Wnonportable-include-path]
    #include "~/Desktop/instabugger/testertest/ios/Pods/Target Support Files/instabug/instabug-prefix.pch"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "~/Desktop/instabugger/testertest/ios/Pods/Target Support Files/Instabug/instabug-prefix.pch"
    1 warning generated.
    28 warnings generated.
    ~/Desktop/instabugger/testertest/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'instabug/InstabugFlutterPlugin.h' file not found
    #import <instabug/InstabugFlutterPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 5s.
```

My specs:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G84, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)
```

Cocoapods is at `1.7.5`.

**Note:** Everything seems to work as expected when running a ObjC based project.

**Comment by satjawat** [comment]
@hffmnn I got the same error. The problem remains.

**Comment by HeshamMegid** [comment]
Thanks for all the details! Just letting you know that we're looking into the issue. Will update you as soon as we have a fix.

**Comment by alyezz** [comment]
@hffmnn we have renamed the package on pub back to `instabug_flutter`, the package `instabug` is now deprecated.

**Comment by satjawat** [comment]
I updated to the new version but when I call to show the Bug report but nothing happens.

**Comment by hffmnn** [comment]
I did a quick test in my project and repeated the steps for a new project I described above and it seems to work as expected. On `Instabug.show()` the Alert shows up.

@satjawat I can not reproduce your problem. Can you describe what you did?

**Comment by HeshamMegid** [comment]
@satjawat can you please confirm that you have the correct app token with no leading or trailing whitespace?

I'm closing this as the original issue has been resolved. @satjawat please go ahead and open a new issue if you're still not able to get the SDK to show up.
